### PR TITLE
Fix #338 avoid moving cursor to the end of contents when focus on textarea/input

### LINKED ISSUE #338: iOS 8.1: Focus on input (filled with text) pushes cursor out of bounds
Can use http://ftlabs.github.io/fastclick/examples/input.html or http://ftlabs.github.io/fastclick/examples/focus.html to test.

Seems to only show up on iOS 8 Safari. When an input element is filled with text, and then refocused, cursor moves to the end of the text, but incorrectly places the cursor outside of the input's bounds.

This can lead to user confusion, especially when the text string is long enough to push the cursor off-screen.

fastclick_ios8_issue

### PR DESCRIPTION
**Pull request by nutti**
Fixed #338.
And this patch also fixed when input type is text.
This patch includes new test as tests/338.html.

### CODE REVIEW

**Comment by paulfalgout** [comment]
Hrmm for me it makes a email input completely not clickable

**Comment by nutti** [comment]
@paulfalgout 

Sorry for my late response.
Thanks for your report.

Is this phenomenon occurred when input tag is ```type="password"``` ?
If so, I think this problem will be fixed soon.

**Comment by paulfalgout** [comment]
for us it's occurring on type="email"

**Comment by nutti** [comment]
OK, I fixed this bug.
please try new patch.

**Comment by nutti** [comment]
Fixed for other input types.

**Comment by nutti** [comment]
There is no response about this PR.
So close it.

**Pull request closed without merging**
